// GENERATED by scripts/sync-version.js from android/app/build.gradle.
// Do not edit: change versionName in build.gradle and build again.

export const APP_VERSION = '1.0';
export const ANDROID_PACKAGE_ID = 'com.trustlab.mydiary';
export const PLAY_STORE_URL = `https://play.google.com/store/apps/details?id=${ANDROID_PACKAGE_ID}`;
