#!/usr/bin/env node
/*
 * One version for the whole app.
 *
 * The source of truth is `versionName` in android/app/build.gradle. This
 * script copies it to:
 *   - src/config/appVersion.ts   (what the running app compares with the store)
 *   - ios/MyDiary.xcodeproj      (MARKETING_VERSION, the iOS version)
 *
 * Gradle runs it before every Android build; run `npm run sync-version`
 * before an iOS archive. Never edit appVersion.ts by hand.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const gradle = path.join(root, 'android/app/build.gradle');
const target = path.join(root, 'src/config/appVersion.ts');
const pbxproj = path.join(root, 'ios/MyDiary.xcodeproj/project.pbxproj');

const gradleText = fs.readFileSync(gradle, 'utf8');
const name = gradleText.match(/^\s*versionName\s+"([^"]+)"/m);
const id = gradleText.match(/^\s*applicationId\s+"([^"]+)"/m);
if (!name || !id) {
  console.error('sync-version: versionName or applicationId not found in build.gradle');
  process.exit(1);
}
const version = name[1];
const packageId = id[1];

const out = `// GENERATED by scripts/sync-version.js from android/app/build.gradle.
// Do not edit: change versionName in build.gradle and build again.

export const APP_VERSION = '${version}';
export const ANDROID_PACKAGE_ID = '${packageId}';
export const PLAY_STORE_URL = \`https://play.google.com/store/apps/details?id=\${ANDROID_PACKAGE_ID}\`;
`;
if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== out) {
  fs.writeFileSync(target, out);
  console.log(`sync-version: appVersion.ts -> ${version}`);
}

let proj = fs.readFileSync(pbxproj, 'utf8');
const next = proj.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${version};`);
if (next !== proj) {
  fs.writeFileSync(pbxproj, next);
  console.log(`sync-version: iOS MARKETING_VERSION -> ${version}`);
}
